language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

sudo: false

env:
  matrix:
    - RUN=lint
    - RUN=test

matrix:
  fast_finish: true

cache:
  - apt

addons:
  apt:
    packages:
      - nginx
      - realpath
  hosts:
    - vanilla.test

install:
  - composer install -o
  - if [ $RUN != 'lint' ]; then tests/travis/nginx/install-nginx.sh; fi

script:
  - tests/run-tests.sh